Repository copper-project/copper-rs, pull requests merged in 2025-05, with the labels that each got.

#304 [CHORE] add deepwiki on README
  README.md
Labels: enhancement

#306 [FIX] use tempfile instead of /tmp
  components/sinks/cu_rp_sn754410/Cargo.toml
  components/sinks/cu_rp_sn754410/tests/sn754410_tester.rs
  components/sources/cu_ads7883/Cargo.toml
  components/sources/cu_ads7883/tests/ads7883_tester.rs
  components/sources/cu_gstreamer/Cargo.toml
  components/sources/cu_gstreamer/tests/gstreamer_tester.rs
  components/sources/cu_hesai/tests/hesai_tester.rs
  components/sources/cu_livox/tests/livox_tester.rs
  components/sources/cu_wt901/Cargo.toml
  components/sources/cu_wt901/tests/wt901_tester.rs
  examples/cu_config_variation/Cargo.toml
  examples/cu_config_variation/src/main.rs
  examples/cu_iceoryx2/Cargo.toml
  examples/cu_iceoryx2/src/bin/downstream.rs
  examples/cu_iceoryx2/src/bin/upstream.rs
  examples/cu_logging_size/src/main.rs
  examples/cu_monitoring/Cargo.toml
  examples/cu_monitoring/src/main.rs
  examples/cu_multisources/Cargo.toml
  examples/cu_multisources/src/main.rs
  templates/cu_full/src/main.rs
Labels: enhancement

#319 [FIX] fix logs path for template helper bin
  templates/cu_full/bin/cl
  templates/cu_full/bin/log
Labels: bug

#303 [CHORE] bump bevy to 0.16
  .config/_typos.toml
  Cargo.toml
  examples/cu_rp_balancebot/Cargo.toml
  examples/cu_rp_balancebot/src/sim.rs
  examples/cu_rp_balancebot/src/world/mod.rs
Labels: dependencies

#318 [FEAT] compile-time log-level macro
  .github/workflows/general.yml
  .github/workflows/weekly.yml
  components/sources/cu_v4l/src/lib.rs
  core/cu29/Cargo.toml
  core/cu29_export/src/lib.rs
  core/cu29_helpers/tests/end2end.rs
  core/cu29_log/README.md
  core/cu29_log/src/lib.rs
  core/cu29_log_derive/Cargo.toml
  core/cu29_log_derive/src/lib.rs
  core/cu29_log_runtime/src/lib.rs
  core/cu29_runtime/src/log.rs
  core/cu29_runtime/src/monitoring.rs
Labels: enhancement

#321 [FIX] (cu29_log) fix README
  core/cu29_log/README.md
Labels: documentation

#323 [FIX] (cu-msp-lib) add bincode feature flag gate fortest
  components/common/cu_msp_lib/src/structs.rs
Labels: bug

#322 [FIX] (cu_rp_gpio) hardware flag instead of not mock flag for Mac compabiibility
  components/sinks/cu_rp_gpio/src/lib.rs
Labels: bug

#324 [CHORE] replace lazy_static by std::sync::OnceLock
  components/sinks/cu_rp_gpio/Cargo.toml
  components/sinks/cu_rp_gpio/src/lib.rs
  core/cu29_log_derive/Cargo.toml
  core/cu29_log_derive/src/index.rs
Labels: enhancement

#329 [CHORE] Move CuArrayVec from cu_apriltag to cu29_runtime
  components/tasks/cu_apriltag/src/lib.rs
  core/cu29_runtime/src/payload.rs
  core/cu29_runtime/tests/payload_test.rs
Labels: enhancement

#331 [CHORE] Bump dependency for the cache-path crate
  examples/cu_rp_balancebot/Cargo.toml
Labels: dependencies

#328 [FEAT] Implement modular configuration
  README.md
  core/cu29_derive/src/lib.rs
  core/cu29_derive/tests/compile_fail/copper_runtime/invalid_config_file.stderr
  core/cu29_derive/tests/compile_fail/cu_msg/invalid_config_file.stderr
  core/cu29_derive/tests/compile_fail/cu_msg/non_existent_id.stderr
  core/cu29_runtime/src/config.rs
  core/cu29_runtime/tests/includes.rs
  core/cu29_runtime/tests/modular_config.rs
  doc/modular_config.md
  examples/modular_config_example/README.md
  examples/modular_config_example/base.ron
  examples/modular_config_example/main_config.ron
  examples/modular_config_example/motors.ron
Labels: documentation, enhancement

#332 [FEAT] nix setup
  support/nix/README.md
  support/nix/flake.nix
  support/nix/shell.nix
Labels: enhancement

#316 [FEAT] Add ROS compatible zenoh sink
  Cargo.toml
  components/payloads/cu_ros_payloads/Cargo.toml
  components/payloads/cu_ros_payloads/src/builtin.rs
  components/payloads/cu_ros_payloads/src/lib.rs
  components/payloads/cu_ros_payloads/src/sensor_msgs.rs
  components/payloads/cu_ros_payloads/src/std_msgs.rs
  components/sinks/cu_zenoh_ros_sink/Cargo.toml
  components/sinks/cu_zenoh_ros_sink/README.md
  components/sinks/cu_zenoh_ros_sink/build.rs
  components/sinks/cu_zenoh_ros_sink/src/attachment.rs
  components/sinks/cu_zenoh_ros_sink/src/error.rs
  components/sinks/cu_zenoh_ros_sink/src/keyexpr.rs
  components/sinks/cu_zenoh_ros_sink/src/lib.rs
  components/sinks/cu_zenoh_ros_sink/src/liveliness.rs
  components/sinks/cu_zenoh_ros_sink/src/node.rs
  components/sinks/cu_zenoh_ros_sink/src/topic.rs
  examples/cu_zenoh_ros/Cargo.toml
  examples/cu_zenoh_ros/README.md
  examples/cu_zenoh_ros/build.rs
  examples/cu_zenoh_ros/copperconfig.ron
  examples/cu_zenoh_ros/src/main.rs
Labels: enhancement
